### ISSUE TITLE
Predicted labels do not appear.

### ISSUE THREAD

**Issue by E4CEeg** [PRBonn/4DMOS#10]
Hello,
Thank you for your work again. I would like to know how the test data annotated. I have annotated Kitti raw data using https://github.com/jbehley/point_labeler this tool and successfully trained my model.  However, after testing the raw sequences and getting the labels when I open the predicted label in annotation tool, it does not give any prediction.

![Screenshot from 2022-08-10 13-22-08](https://user-images.githubusercontent.com/18581634/183891043-f284a9b2-e953-4c03-9c24-3a5139b1f167.jpg)

Just looks like everything is gray. 

I have tried to change def to_label in confidences_to_label.py. But i have no luck. Can you please look into this ?
Thank you.

**Comment by benemer** [comment]
Hi @E4CEeg,

Did you verify that your annotated data is correct? One way to check would be to use the visualizer of the [SemanticKITTI API](https://github.com/PRBonn/semantic-kitti-api). You can also use this tool to visualize your MOS predictions. I never used the point labeler to visualize predictions.

Best
Benedikt

**Comment by benemer** [comment]
Did you find any problem on our side? Otherwise, I would close this issue since it seems to be related to the point labeling rather than the 4DMOS code.

**Comment by E4CEeg** [comment]
Hello,

As you have suggested, I have tried visualizer of the SemanticKitti API. My annotated labels are shown in the visualizer.
However, my predictions are not shown it. First, I have trained the model with my annotated data. With my trained model, I have tried to predict my own custom data and sequence 11 of SemanticKitti. Both of them do not show any result in the visualizer. Then I have used 10scans.ckpt to predict my own data and same as sequence 11 from SemanticKitti. However, still the results of both of them do not show any moving object.

**Comment by benemer** [comment]
Which labels are you using for annotation?

It should definitely work predicting moving objects with the pre-trained ```10scans.ckpt``` model on sequence 11 and visualizing them with the SemanticKITTI API. Can you post the commands you use for running the inference scripts and what your predictions folder looks like?

**Comment by E4CEeg** [comment]
Hello, sorry for the late reply. 
I am also confused about the result. So I have started again, using only the pre-trained model 10scans and semantickitti sequence 11.
Here i am running the given trained model.
![image](https://user-images.githubusercontent.com/18581634/185101465-b36837ca-bedd-4d7f-b982-4cf3855ba509.png)
![image](https://user-images.githubusercontent.com/18581634/185101903-8886881a-448b-4b55-a102-f4dfcb1d26c0.png)
Here is the folder file structure.
![image](https://user-images.githubusercontent.com/18581634/185102167-d7344d4a-0994-4072-afb9-4fc0bc739e43.png)
Here , I am running the visualizer.
![image](https://user-images.githubusercontent.com/18581634/185102276-1cac8648-c596-4919-bcc8-1a63968d2917.png)
And this is the shown result. There is a moving van in between scan21-31.
This is the scan 22.
![image](https://user-images.githubusercontent.com/18581634/185103318-fb02c12a-e173-4537-b27c-754c2ba29e1b.png)
This is the scan 29
![image](https://user-images.githubusercontent.com/18581634/185104753-941dd4c0-1435-4553-a637-3c7a5c93c8ef.png)

Unfortunately, in the visualizer, nothing shows up.

**Comment by benemer** [comment]
By running ```visualize.py```, you are using the semantic segmentation config of SemanticKITTI and not the MOS config file. The problem is the wrong label mapping since moving objects are labeled with the class ID 251 which is not present in the SemanticKITTI config for semantic segmentation. Therefore, no labels are displayed. You need to run either

```
./visualize_mos.py --sequence 8 --dataset /path/to/dataset
```

while providing labels in the labels folder or you specify the path to the predictions as described in the [README](https://github.com/PRBonn/4DMOS/edit/master/Readme.md#evaluation-and-visualization):

```
./visualize_mos.py --sequence 8 --dataset /path/to/dataset --predictions /path/to/4DMOS/predictions/ID/POSES/labels/STRATEGY/
```

**Comment by E4CEeg** [comment]
Oh you're right. That was a very stupid error. Thank you very much.
