### ISSUE TITLE
Custom visualization - mismatch data shape

### ISSUE THREAD

**Issue by dnn-6** [PRBonn/4DMOS#17]
Hi, 

I'm trying to use the pretrained models for inference on custom data. I first convert my data to 4DMOS format, make it be a new sequence and run predict_confidences.py and confidence_to_labels.py with no issue.

Then, I would like to use the predicted labels to filter my raw point clouds. However, if I open the raw point cloud and the predicted label file, they do not have the same shape. Also, the shape of the label does not match the combination of several raw point clouds.

How should I attempt this?

Thank you!

**Comment by benemer** [comment]
Hey!

> However, if I open the raw point cloud and the predicted label file, they do not have the same shape.

This should usually not happen, since 4DMOS does not do any downsampling or clipping. Can you check the if the size of your downsampled point clouds match those from the raw point clouds?

> Also, the shape of the label does not match the combination of several raw point clouds.

Sorry, I don't understand what you mean. What do you mean with `match the combination`?

Best
Benedikt
