### ISSUE TITLE
Docker build issue

### ISSUE THREAD

**Issue by haider8645** [PRBonn/4DMOS#25]
Hello,

while running make build, the build process gets stuck at 

```
Step 16/17 : RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
 ---> Running in ad1c2386776b
Adding user `user' ...
Adding new user `user' (1545614636) with group `user' ...
Creating home directory `/home/user' ...
Copying files from `/etc/skel' ...

```
I waited but it does not proceed. Any idea why this might be happening?

Best,
Haider

**Comment by benemer** [comment]
Hey, I think the problem is your large uid (1545614636), see [here](https://github.com/docker/hub-feedback/issues/2263#issuecomment-1205423533).

Please try with replacing this line
```Dockerfile
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
```
in the `Dockerfile` with

```Dockerfile
RUN useradd --no-log-init -m -s /bin/bash --uid $USER_ID --gid $GROUP_ID user
```

**Comment by haider8645** [comment]
Than you!
