### ISSUE TITLE
Does it have scan_cleaner utils like LM-Net?

### ISSUE THREAD

**Issue by Lizhijian-123** [PRBonn/4DMOS#27]
Thanks for you code.
Cloud this project get a clean point cloud(no moving object) like Lidar mos?

**Comment by benemer** [comment]
Hi!

Yes, you could predict moving objects in the window of scans (with our without the binary Bayes filter) and only add the predicted non-moving points to your map.

Best
Benedikt

**Comment by Lizhijian-123** [comment]
> Hi!
> 
> Yes, you could predict moving objects in the window of scans (with our without the binary Bayes filter) and only add the predicted non-moving points to your map.
> 
> Best Benedikt

I'm sorry that I'm very new in this area. Could you give me a simple guide? Thank you very much.

**Comment by benemer** [comment]
Sorry, I need some more details. What data are you using and what exactly are you trying to do with it?

**Comment by Lizhijian-123** [comment]
> Sorry, I need some more details. What data are you using and what exactly are you trying to do with it?



> Sorry, I need some more details. What data are you using and what exactly are you trying to do with it?

Sorry, I didn't express myself to clear it, I am using SemanticKITTI and your Pretrained  Models, and I would like to get a bin file that removes detected moving objects from each point cloud frame.Can this be achieved?

**Comment by benemer** [comment]
Okay, that's easy:

1. Use this repository to get the 4DMOS predictions as `.label` files for the desired sequence (instructions in the README).
2. Use [this](https://github.com/PRBonn/LiDAR-MOS/blob/main/utils/scan_cleaner.py) script from LMNet to clean the scans. Note that you need to modify the config file.

**Comment by Lizhijian-123** [comment]
> 

thanks
