### ISSUE TITLE
some questions about MinkowskiEngine

### ISSUE THREAD

**Issue by pange1802703882** [PRBonn/4DMOS#32]
Thanks for your nice repo firstly. And I find it looks diffcult to export onnx model for the tensorRT deploy because of MinkowskiEngine. I want to ask how to  export  onnx or deploy tensorRT in Orin?  Thank you !!!

**Comment by benemer** [comment]
Hey!

Thanks for your feedback. I have no experience with tensorRT, but maybe have a look at https://github.com/NVIDIA/MinkowskiEngine/issues/321 and https://github.com/NVIDIA/MinkowskiEngine/issues/402.

Closed since not related to this repository.
