### ISSUE TITLE
UserWarning: GPUs can't support floating point data

### ISSUE THREAD

**Issue by lxdunan** [PRBonn/4DMOS#33]
UserWarning: GPUs can't support floating point data with more than 32-bits, precision will be lost due to downcasting to 32-bit float.
  warnings.warn(F64_PRECISION_WARNING)
Within the code, Tthe model can be either 64-bit or 32-bit. However, why is it throwing an error here?

**Comment by benemer** [comment]
Can you please be more precise? Which script are you running? Which data are you using? Did you modify the code in any way?

We use floating point precision everywhere and therefore both model parameters and data are represented as `torch.float32`.

**Comment by lxdunan** [comment]
Thank you very much for your response. The issue occurred when I ran the visualization, as shown in the image below. I haven't modified the code; I'm using the SemanticKITTI dataset.The problem also occurred in MotionSeg3D.

**Comment by benemer** [comment]
Well, then it is a problem of the SemanticKITTI visualizer and not of 4DMOS. Can you please open an issue there?

Best
Benedikt
