### ISSUE TITLE
Which sequence is used as the validation sequence for the Apollo dataset

### ISSUE THREAD

**Issue by momoshiki1** [PRBonn/4DMOS#36]
Hello, I would like to know which sequence 4DMOS in the 0-4 sequence of Apollo data is used for training and which sequence is used for validation

**Comment by benemer** [comment]
4DMOS does not use Apollo for training, we directly use the model that was trained on SemanticKITTI. For the training setup of LMNet please check the referenced AutoMOS paper.

We use the Apollo sequences 2 and 3 for evaluation as stated in our paper at the end of section IV A.
