### ISSUE TITLE
mos4d_pipeline：Command not found

### ISSUE THREAD

**Issue by iwander-all** [PRBonn/4DMOS#40]
Hi, after install 4DMOS with `make install`, when I run `mos4d_pipeline --help`, it shows `mos4d_pipeline：Command not found`, how to solve it, thanks

**Comment by iwander-all** [comment]
install is success:

`Using pip 23.2.1 from /usr/local/anaconda3/lib/python3.11/site-packages/pip (python 3.11)
Defaulting to user installation because normal site-packages is not writeable
Processing /media/hunkyu/SuperBigDisk/DeepLearning/net/MOS/4DMOS
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=61.0
    Obtaining dependency information for setuptools>=61.0 from https://files.pythonhosted.org/packages/cb/9c/9ad11ac06b97e55ada655f8a6bea9d1d3f06e120b178cd578d80e558191d/setuptools-74.1.2-py3-none-any.whl.metadata
    Using cached setuptools-74.1.2-py3-none-any.whl.metadata (6.7 kB)
  Using cached setuptools-74.1.2-py3-none-any.whl (1.3 MB)
  Installing collected packages: setuptools
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
  conda-repo-cli 1.0.75 requires requests_mock, which is not installed.
  spyder 5.4.3 requires pyqt5<5.16, which is not installed.
  spyder 5.4.3 requires pyqtwebengine<5.16, which is not installed.
  conda-repo-cli 1.0.75 requires clyent==1.2.1, but you have clyent 1.2.2 which is incompatible.
  conda-repo-cli 1.0.75 requires PyYAML==6.0.1, but you have pyyaml 6.0 which is incompatible.
  Successfully installed setuptools-74.1.2
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  writing src/mos4d.egg-info/PKG-INFO
  writing dependency_links to src/mos4d.egg-info/dependency_links.txt
  writing entry points to src/mos4d.egg-info/entry_points.txt
  writing requirements to src/mos4d.egg-info/requires.txt
  writing top-level names to src/mos4d.egg-info/top_level.txt
  reading manifest file 'src/mos4d.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'src/mos4d.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info
  writing /tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/dependency_links.txt
  writing entry points to /tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/entry_points.txt
  writing requirements to /tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/requires.txt
  writing top-level names to /tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/top_level.txt
  writing manifest file '/tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-modern-metadata-2ndoipya/mos4d.egg-info/SOURCES.txt'
  creating '/tmp/pip-modern-metadata-2ndoipya/mos4d-1.0.0.dist-info'
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: kiss-icp>=1.0.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from mos4d==1.0.0) (1.0.0)
Requirement already satisfied: diskcache>=5.3.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from mos4d==1.0.0) (5.6.3)
Requirement already satisfied: pytorch-lightning>=1.6.4 in /home/hunkyu/.local/lib/python3.11/site-packages (from mos4d==1.0.0) (2.4.0)
Requirement already satisfied: natsort in /home/hunkyu/.local/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (8.4.0)
Requirement already satisfied: numpy in /usr/local/anaconda3/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (1.24.3)
Requirement already satisfied: plyfile in /home/hunkyu/.local/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (1.1)
Requirement already satisfied: pydantic>=2 in /home/hunkyu/.local/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (2.9.1)
Requirement already satisfied: pydantic-settings in /home/hunkyu/.local/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (2.5.2)
Requirement already satisfied: pyquaternion in /home/hunkyu/.local/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (0.9.9)
Requirement already satisfied: rich in /home/hunkyu/.local/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (13.8.1)
Requirement already satisfied: tqdm in /usr/local/anaconda3/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (4.65.0)
Requirement already satisfied: typer[all]>=0.6.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from kiss-icp>=1.0.0->mos4d==1.0.0) (0.12.5)
Requirement already satisfied: torch>=2.1.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from pytorch-lightning>=1.6.4->mos4d==1.0.0) (2.4.1)
Requirement already satisfied: PyYAML>=5.4 in /usr/local/anaconda3/lib/python3.11/site-packages (from pytorch-lightning>=1.6.4->mos4d==1.0.0) (6.0)
Requirement already satisfied: fsspec[http]>=2022.5.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from pytorch-lightning>=1.6.4->mos4d==1.0.0) (2023.4.0)
Requirement already satisfied: torchmetrics>=0.7.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from pytorch-lightning>=1.6.4->mos4d==1.0.0) (1.4.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from pytorch-lightning>=1.6.4->mos4d==1.0.0) (23.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from pytorch-lightning>=1.6.4->mos4d==1.0.0) (4.12.2)
Requirement already satisfied: lightning-utilities>=0.10.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from pytorch-lightning>=1.6.4->mos4d==1.0.0) (0.11.7)
Requirement already satisfied: requests in /usr/local/anaconda3/lib/python3.11/site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (2.31.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/anaconda3/lib/python3.11/site-packages (from fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (3.8.5)
Requirement already satisfied: setuptools in /usr/local/anaconda3/lib/python3.11/site-packages (from lightning-utilities>=0.10.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (68.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from pydantic>=2->kiss-icp>=1.0.0->mos4d==1.0.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.3 in /home/hunkyu/.local/lib/python3.11/site-packages (from pydantic>=2->kiss-icp>=1.0.0->mos4d==1.0.0) (2.23.3)
Requirement already satisfied: filelock in /usr/local/anaconda3/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (3.9.0)
Requirement already satisfied: sympy in /usr/local/anaconda3/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (1.11.1)
Requirement already satisfied: networkx in /usr/local/anaconda3/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (3.1)
Requirement already satisfied: jinja2 in /usr/local/anaconda3/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (3.1.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/hunkyu/.local/lib/python3.11/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (12.6.68)
WARNING: typer 0.12.5 does not provide the extra 'all'
Requirement already satisfied: click>=8.0.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from typer[all]>=0.6.0->kiss-icp>=1.0.0->mos4d==1.0.0) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /home/hunkyu/.local/lib/python3.11/site-packages (from typer[all]>=0.6.0->kiss-icp>=1.0.0->mos4d==1.0.0) (1.5.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from rich->kiss-icp>=1.0.0->mos4d==1.0.0) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from rich->kiss-icp>=1.0.0->mos4d==1.0.0) (2.15.1)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from pydantic-settings->kiss-icp>=1.0.0->mos4d==1.0.0) (0.21.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (22.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (2.0.4)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (6.0.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (1.8.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/anaconda3/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (1.2.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->kiss-icp>=1.0.0->mos4d==1.0.0) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/anaconda3/lib/python3.11/site-packages (from jinja2->torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/anaconda3/lib/python3.11/site-packages (from requests->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/anaconda3/lib/python3.11/site-packages (from requests->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/anaconda3/lib/python3.11/site-packages (from requests->fsspec[http]>=2022.5.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in /usr/local/anaconda3/lib/python3.11/site-packages (from sympy->torch>=2.1.0->pytorch-lightning>=1.6.4->mos4d==1.0.0) (1.3.0)
Building wheels for collected packages: mos4d
  Running command Building wheel for mos4d (pyproject.toml)
  running bdist_wheel
  running build
  running build_py
  copying src/mos4d/cli.py -> build/lib/mos4d
  running egg_info
  writing src/mos4d.egg-info/PKG-INFO
  writing dependency_links to src/mos4d.egg-info/dependency_links.txt
  writing entry points to src/mos4d.egg-info/entry_points.txt
  writing requirements to src/mos4d.egg-info/requires.txt
  writing top-level names to src/mos4d.egg-info/top_level.txt
  reading manifest file 'src/mos4d.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'src/mos4d.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/mos4d
  copying build/lib/mos4d/cli.py -> build/bdist.linux-x86_64/wheel/./mos4d
  creating build/bdist.linux-x86_64/wheel/mos4d/config
  copying build/lib/mos4d/config/config.py -> build/bdist.linux-x86_64/wheel/./mos4d/config
  copying build/lib/mos4d/config/parser.py -> build/bdist.linux-x86_64/wheel/./mos4d/config
  copying build/lib/mos4d/config/__init__.py -> build/bdist.linux-x86_64/wheel/./mos4d/config
  creating build/bdist.linux-x86_64/wheel/mos4d/datasets
  copying build/lib/mos4d/datasets/apollo.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/generic.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/helimos.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/kitti.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/kitti_tracking.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/mcap.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/mos4d_dataset.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/nuscenes.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/ouster.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/rosbag.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/datasets/__init__.py -> build/bdist.linux-x86_64/wheel/./mos4d/datasets
  copying build/lib/mos4d/metrics.py -> build/bdist.linux-x86_64/wheel/./mos4d
  copying build/lib/mos4d/minkunet.py -> build/bdist.linux-x86_64/wheel/./mos4d
  copying build/lib/mos4d/mos4d.py -> build/bdist.linux-x86_64/wheel/./mos4d
  copying build/lib/mos4d/odometry.py -> build/bdist.linux-x86_64/wheel/./mos4d
  copying build/lib/mos4d/pipeline.py -> build/bdist.linux-x86_64/wheel/./mos4d
  copying build/lib/mos4d/training_module.py -> build/bdist.linux-x86_64/wheel/./mos4d
  creating build/bdist.linux-x86_64/wheel/mos4d/utils
  copying build/lib/mos4d/utils/augmentation.py -> build/bdist.linux-x86_64/wheel/./mos4d/utils
  copying build/lib/mos4d/utils/cache.py -> build/bdist.linux-x86_64/wheel/./mos4d/utils
  copying build/lib/mos4d/utils/pipeline_results.py -> build/bdist.linux-x86_64/wheel/./mos4d/utils
  copying build/lib/mos4d/utils/save.py -> build/bdist.linux-x86_64/wheel/./mos4d/utils
  copying build/lib/mos4d/utils/seed.py -> build/bdist.linux-x86_64/wheel/./mos4d/utils
  copying build/lib/mos4d/utils/visualizer.py -> build/bdist.linux-x86_64/wheel/./mos4d/utils
  copying build/lib/mos4d/utils/__init__.py -> build/bdist.linux-x86_64/wheel/./mos4d/utils
  running install_egg_info
  Copying src/mos4d.egg-info to build/bdist.linux-x86_64/wheel/./mos4d-1.0.0-py3.11.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/mos4d-1.0.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-2xvqojaq/.tmp-uj1kimen/mos4d-1.0.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'mos4d/cli.py'
  adding 'mos4d/metrics.py'
  adding 'mos4d/minkunet.py'
  adding 'mos4d/mos4d.py'
  adding 'mos4d/odometry.py'
  adding 'mos4d/pipeline.py'
  adding 'mos4d/training_module.py'
  adding 'mos4d/config/__init__.py'
  adding 'mos4d/config/config.py'
  adding 'mos4d/config/parser.py'
  adding 'mos4d/datasets/__init__.py'
  adding 'mos4d/datasets/apollo.py'
  adding 'mos4d/datasets/generic.py'
  adding 'mos4d/datasets/helimos.py'
  adding 'mos4d/datasets/kitti.py'
  adding 'mos4d/datasets/kitti_tracking.py'
  adding 'mos4d/datasets/mcap.py'
  adding 'mos4d/datasets/mos4d_dataset.py'
  adding 'mos4d/datasets/nuscenes.py'
  adding 'mos4d/datasets/ouster.py'
  adding 'mos4d/datasets/rosbag.py'
  adding 'mos4d/utils/__init__.py'
  adding 'mos4d/utils/augmentation.py'
  adding 'mos4d/utils/cache.py'
  adding 'mos4d/utils/pipeline_results.py'
  adding 'mos4d/utils/save.py'
  adding 'mos4d/utils/seed.py'
  adding 'mos4d/utils/visualizer.py'
  adding 'mos4d-1.0.0.dist-info/LICENSE'
  adding 'mos4d-1.0.0.dist-info/METADATA'
  adding 'mos4d-1.0.0.dist-info/WHEEL'
  adding 'mos4d-1.0.0.dist-info/entry_points.txt'
  adding 'mos4d-1.0.0.dist-info/top_level.txt'
  adding 'mos4d-1.0.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for mos4d (pyproject.toml) ... done
  Created wheel for mos4d: filename=mos4d-1.0.0-py3-none-any.whl size=55913 sha256=1dc1b35fd3e1987f13b15a23d1f69df0e9b07ff52f5f215e64640231c6883890
  Stored in directory: /tmp/pip-ephem-wheel-cache-un64b4wr/wheels/d8/9c/9e/b2755b12150453768881c892bbf4945e195b607d1d199e2f34
Successfully built mos4d
Installing collected packages: mos4d
  Attempting uninstall: mos4d
    Found existing installation: mos4d 1.0.0
    Uninstalling mos4d-1.0.0:
      Removing file or directory /home/hunkyu/.local/bin/4dmos_pipeline
      Removing file or directory /home/hunkyu/.local/lib/python3.11/site-packages/mos4d-1.0.0.dist-info/
      Removing file or directory /home/hunkyu/.local/lib/python3.11/site-packages/mos4d/
      Successfully uninstalled mos4d-1.0.0
  changing mode of /home/hunkyu/.local/bin/4dmos_pipeline to 775
Successfully installed mos4d-1.0.0
`

**Comment by benemer** [comment]
Hi,

Sorry, the name was wrong in the `pyproject.toml`. I just fixed it, please pull and try again :)
