### ISSUE TITLE
Scan and Label don't contain same number of points?

### ISSUE THREAD

**Issue by pengboyemo** [PRBonn/4DMOS#43]
Hi, @benemer 
Below the first picture is the result labels of 4dmos, when i use semantic-kitti-api script visualize_mos.py but get a error like the second picture, why the reason for this?
![image](https://github.com/user-attachments/assets/908bc0c2-3b9f-423c-b2e1-e7a8d32dea7c)

![image](https://github.com/user-attachments/assets/b9a555ec-eb6a-4663-8982-112946ff97af)

**Comment by benemer** [comment]
Which configuration do you use? For evaluation on SemanticKITTI, you can pass the kitti config to classify moving/non-moving for all points in the scan.

As you can see from the error message, there are less labels in your predictions than points Most likely, your max_range for mos was not set to -1 which disables the clipping and/or the min_range was not set to 0.

**Comment by pengboyemo** [comment]
Thanks for your replay, below the first file the SemanticKITTI configure file which i changed it's format yaml to txt for uploading, the second file is 4dmos configure file, but i am not sure 4DMOS configure like kitti.yaml or other file is need to be modified? 
[semantic-kitti-mos.txt](https://github.com/user-attachments/files/18251864/semantic-kitti-mos.txt)
[kitti.txt](https://github.com/user-attachments/files/18251876/kitti.txt)

**Comment by benemer** [comment]
You do not need to modify the file, just pass the path to the kitti.txt (the 4DMOS config file) using the -c flag when running the pipeline.

**Comment by pengboyemo** [comment]
I have get the right result in the below picture, i will close my issue, thanks for your help and appreciate your work.
![image](https://github.com/user-attachments/assets/46998315-6c81-426c-bfe5-e164431c31c4)
![image](https://github.com/user-attachments/assets/ba17131a-3c36-46c8-8d57-3b72abf6c418)
